name: Go

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions:
  contents: read

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v7
      with:
        persist-credentials: false

    - name: Setup Go
      uses: actions/setup-go@v7
      with:
        go-version-file: 'go.mod'

    - name: Build
      run: go build -v ./...

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:

    - name: Check out code
      uses: actions/checkout@v7
      with:
        persist-credentials: false

    - name: Setup Go
      uses: actions/setup-go@v7
      with:
        go-version-file: 'go.mod'

    - name: Test
      run: go test ./...


  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: build
    steps:

    - name: Check out code
      uses: actions/checkout@v7
      with:
        persist-credentials: false

    - name: Setup Go
      uses: actions/setup-go@v7
      with:
        go-version-file: 'go.mod'

    - name: Run Linter
      uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a #v9.3.0
      with:
        version: v2.8.0
